---
- name: Deploy
  hosts: kafka
  gather_facts: false
  become: yes
  tasks:
    - name: Get env file content
      include_vars:
        file: env.yml
        name: env

    - name: Update and Upgrade
      apt:
        upgrade: dist
        update_cache: yes

    - name: Install system packages
      apt:
        name:
          - python3
          - git
          - neovim
          - curl
        state: present

    - name: copy python scripts
      copy:
        src: ./scheduled/
        dest: /home/notedwin/scheduled/
        owner: notedwin
        group: notedwin
        mode: 0644

    - name: copy .env
      copy:
        src: .env
        dest: /home/notedwin/scheduled/
        owner: notedwin
        group: notedwin
        mode: 0644

    - name: Run CRON job to export cloudflare data every 4 days.
      cron:
        name: "export_data"
        user: "notedwin"
        weekday: "*/4"
        minute: "0"
        hour: "0"
        job: "/home/notedwin/scheduled/.venv/bin/python3 /home/notedwin/scheduled/cf_export.py > /home/notedwin/scheduled/cloudflare.log 2>&1"
        state: present

    - name: Run CRON job to export calendar export
      cron:
        name: "export_calendar"
        user: "notedwin"
        weekday: "*/4"
        minute: "0"
        hour: "0"
        job: "/home/notedwin/scheduled/.venv/bin/python3 /home/notedwin/scheduled/cal.py > /home/notedwin/scheduled/cal.log 2>&1"
        state: present
