SELECT
  ZOBJECT.ZVALUESTRING AS "app",
  DATE(DATETIME(ZOBJECT.ZSTARTDATE + 978307200, 'UNIXEPOCH')) AS "date",
  CASE 
    WHEN ZMODEL IS NOT NULL THEN ZMODEL
    ELSE 'Mac'
  END AS "source",
  SUM(ZOBJECT.ZENDDATE - ZOBJECT.ZSTARTDATE) AS "usage"
FROM
  ZOBJECT 
  LEFT JOIN
    ZSTRUCTUREDMETADATA 
  ON ZOBJECT.ZSTRUCTUREDMETADATA = ZSTRUCTUREDMETADATA.Z_PK 
  LEFT JOIN
    ZSOURCE 
  ON ZOBJECT.ZSOURCE = ZSOURCE.Z_PK 
  LEFT JOIN
    ZSYNCPEER
  ON ZSOURCE.ZDEVICEID = ZSYNCPEER.ZDEVICEID
WHERE
  ZOBJECT.ZSTREAMNAME = '/app/usage'
GROUP BY 
1,2,3
ORDER BY 4 DESC


  